title = "Rodrigo Almeida"
baseURL = "https://rodrigoalmeida.pt/"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = "G-QCSW64JHJ8"
enableRobotsTXT = true

[params]
  author = "Rodrigo Almeida"
  description = "AI for Weather & Climate"
  long_description = "Rodrigo Almeida is a Geo-Information, AI Researcher and Cloud Engineer using AI to understand, predict and adapt to our changing climate."
  terminal_path = "rodrigoalmeida" # directory name shown in the CLI prompt
  favicon = "./favicon.svg"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  twitter = "@rodrigo_gtiff"
  social_image = "./social.webp"

  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    fontSize = "14pt"
    pageWidth = "750px"
    avatarSize = "160px"
    colorBlack = "#ffffff"
    colorRed = "#50FA7B"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:rodrigo.almeida94[at]outlook.pt"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/rodrigoalmeida94"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/rodrigomalmeida/"
  [[params.socialIcons]]
    icon = "fab fa-bluesky"
    title = "Bluesky"
    url = "https://bsky.app/profile/rodrigo-gtiff.bsky.social"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "about.md"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "projects.sh"
    url = "/projects"
    weight = 2
  [[menu.main]]
    name = "blog.log"
    url = "/posts"
    weight = 3
  [[menu.main]]
    name = "contact.json"
    url = "/contact"
    weight = 4

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files

[minify]
  minifyOutput = true